### ISSUE TITLE
Support SAM with receiver annotations

### ISSUE THREAD

**Issue by fwcd** [fwcd/kotlin-language-server#216]
### Motivation

The Gradle/Kotlin DSL uses a feature where Kotlin lambdas are not only automatically conformed to an interface, but also use an implicit receiver. Such interfaces are marked with a special annotation, e.g. [`org.gradle.api.HasImplicitReceiver`](https://github.com/gradle/gradle/blob/90d33c9b8153067e30db7b6cc0be96d41e05e7d8/subprojects/base-services/src/main/java/org/gradle/api/HasImplicitReceiver.java) and e.g. used in [`org.gradle.api.Action`](https://github.com/gradle/gradle/blob/90d33c9b8153067e30db7b6cc0be96d41e05e7d8/subprojects/base-services/src/main/java/org/gradle/api/Action.java).

For example: Without compiler support, the Kotlin language server cannot see the implicit `JavaApplication` receiver (which defines `mainClassName`) inside this lambda:

![image](https://user-images.githubusercontent.com/30873659/84083016-1eeff700-a9e1-11ea-9bd8-86be084f3a6f.png)

This might also solve #165.

### Implementation

To support this feature...
* the compiler has to have the [corresponding language feature enabled](https://github.com/JetBrains/kotlin/blob/50165397c701664cd9acdef4f0d084b0194fdfa2/compiler/util/src/org/jetbrains/kotlin/config/LanguageVersionSettings.kt#L149-L152).
    * Note: this might require Kotlin 1.4
        * ...whose support is tracked by the [eap branch](https://github.com/fwcd/kotlin-language-server/tree/kotlin-eap)
    * See also: [the Gradle compiler plugin](https://github.com/gradle/kotlin-dsl-samples/blob/50c4a8d0f144da5b1611a6617fb8a0c960a8774a/subprojects/plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslCompilerPlugins.kt#L51-L58)
* the `ScriptDefinition` used for Gradle/Kotlin DSL scripts must include the correct [`annotationsForSamWithReceivers`](https://github.com/JetBrains/kotlin/blob/c112d37ac1a739f6cb3a90de8edde5f6dd8d2661/plugins/scripting/scripting-compiler-impl/src/org/jetbrains/kotlin/scripting/definitions/ScriptDefinition.kt#L46)
    * In this case: `org.gradle.api.HasImplicitReceiver`
    * Investigate whether this annotation is already registered by `KotlinBuildScript` (one of the [templates used by the language server](https://github.com/fwcd/kotlin-language-server/blob/9e6abbb4d8cb722d3eadb46286da39c33249b6af/server/src/main/kotlin/org/javacs/kt/Compiler.kt#L132))
* the language server possibly needs the [sam-with-receiver](https://github.com/JetBrains/kotlin/tree/master/plugins/sam-with-receiver) compiler plugin
    * ...whose support is tracked by the [corresponding branch](https://github.com/fwcd/kotlin-language-server/tree/sam-with-receiver)
    * The issue there is currently, that the [`kotlin-sam-with-receiver-compiler-plugin` artifact](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-sam-with-receiver-compiler-plugin) does not use the embedded Kotlin compiler's paths (i.e. it uses `com.intellij` instead of `org.jetbrains.kotlin.com.intellij`) and thus throws `AbstractMethodError`s when trying to register with an interface that expects the embedded package name:

<details>

```
Exception in thread "main" java.lang.IllegalStateException: The provided plugin org.jetbrains.kotlin.samWithReceiver.SamWithReceiverComponentRegistrar is not compatible with this version of compiler
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:639)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$ProjectEnvironment.registerExtensionsFromPlugins(KotlinCoreEnvironment.kt:145)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:185)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:125)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:432)
	at org.javacs.kt.CompilationEnvironment.<init>(Compiler.kt:101)
	at org.javacs.kt.Compiler.<init>(Compiler.kt:237)
	at org.javacs.kt.CompilerClassPath.<init>(CompilerClassPath.kt:18)
	at org.javacs.kt.KotlinLanguageServer.<init>(KotlinLanguageServer.kt:21)
	at org.javacs.kt.MainKt.main(Main.kt:42)
Caused by: java.lang.AbstractMethodError: Receiver class org.jetbrains.kotlin.samWithReceiver.SamWithReceiverComponentRegistrar does not define or inherit an implementation of the resolved method 'abstract void registerProjectComponents(org.jetbrains.kotlin.com.intellij.mock.MockProject, org.jetbrains.kotlin.config.CompilerConfiguration)' of interface org.jetbrains.kotlin.compiler.plugin.ComponentRegistrar.
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.registerExtensionsFromPlugins$cli(KotlinCoreEnvironment.kt:631)
	... 9 more
```

</details>

### See also

* [Eclipse Buildship support for Kotlin DSL](https://github.com/eclipse/buildship/issues/222) (which seems to be non-existent currently) (the other direction of support might even be more likely: https://github.com/eclipse/buildship/issues/990)
* [Notes on the SAM with Receiver Compiler Plugin](https://kotlinlang.org/docs/reference/compiler-plugins.html#sam-with-receiver-compiler-plugin)

**Comment by LifeIsStrange** [comment]
That does not fix the issue for older versions but note that Kotlin 1.4 (which should be released in ~a month) bring SAM conversions support without the need of a compiler plugin / annotations
