### ISSUE TITLE
Error while updating symbol index (from vscode-kotlin)

### ISSUE THREAD

**Issue by b1naryth1ef** [fwcd/kotlin-language-server#274]
I'm trying to play around with the latest additions towards symbol indexing via vscode-kotlin, however running into the following error in the output logs (and no indexing appears to work):

```
[Error - 6:07:45 PM] client    Error while updating symbol index
[Error - 6:07:45 PM] java.lang.IllegalArgumentException: Value 'ServerImpl$ServerTransportListenerImpl$1StreamCreated$1ServerStreamCancellationListener' can't be stored to database column because exceeds length (80)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.VarCharColumnType.notNullValueToDB(ColumnType.kt:541)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToDB(ColumnType.kt:37)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.ColumnType.valueToDB(ColumnType.kt:71)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:9)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:53)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.QueriesKt.replace(Queries.kt:156)
[Error - 6:07:45 PM] 	at org.javacs.kt.index.SymbolIndex$refresh$1$1.invoke(SymbolIndex.kt:66)
[Error - 6:07:45 PM] 	at org.javacs.kt.index.SymbolIndex$refresh$1$1.invoke(SymbolIndex.kt:37)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:191)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:190)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
[Error - 6:07:45 PM] 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
[Error - 6:07:45 PM] 	at org.javacs.kt.index.SymbolIndex$refresh$1.apply(SymbolIndex.kt:58)
[Error - 6:07:45 PM] 	at org.javacs.kt.index.SymbolIndex$refresh$1.apply(SymbolIndex.kt:37)
[Error - 6:07:45 PM] 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
[Error - 6:07:45 PM] 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
[Error - 6:07:45 PM] 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
[Error - 6:07:45 PM] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:212)
[Error - 6:07:45 PM] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
[Error - 6:07:45 PM] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
[Error - 6:07:45 PM] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
[Error - 6:07:45 PM] 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
[Error - 6:07:45 PM] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Error - 6:07:45 PM] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Error - 6:07:45 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[Error - 6:07:45 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[Error - 6:07:45 PM] 	at java.base/java.lang.Thread.run(Thread.java:832
```

**Comment by fwcd** [comment]
Hm, yeah, that's unfortunate. A quick fix would be to simply exclude symbols whose name exceeds the maximum length (which has to be some arbitrary value), but that's of course not an ideal solution.

**Comment by fwcd** [comment]
For now, you can set `kotlin.indexing.enabled` to `false` (if needed, at a project level) to disable the indexer.

**Comment by pajatopmr** [comment]
I'm probably missing something here, and it would be good to understand it, but at first glance it appears that a symbol obtained from KLS is used in and breaks some external database which has an arbitrary size limit. I hope I'm wrong because if I'm right, this is not a KLS bug. No way.  So first, am I reading this bug report correctly?

**Comment by fwcd** [comment]
This is/was a KLS a bug, since KLS manages this embedded database and imposes the limit itself ([see here](https://github.com/fwcd/kotlin-language-server/blob/master/server/src/main/kotlin/org/javacs/kt/index/SymbolIndex.kt#L18-L19)). The limit is arbitrary in the sense that it assumes fully-qualified names to be less than 255 characters in length, which may be a bit restrictive, especially considering how long JVM class names often get. It is necessary, however, as symbol indices usually get quite large (as in tens/hundreds of thousands of symbols) and are queried multiple times very often, especially when the user types quickly. I agree that it should be configurable though, so I've opened #275.

**Comment by pajatopmr** [comment]
Very cool. Thanks for the explanation. And #275 make some sense but what makes more sense to me is to overhaul the symbols repository to have no limits and no need for it to be configured. Fwiw.
