### ISSUE TITLE
Go To Definition is broken for symbols in JARs

### ISSUE THREAD

**Issue by daplf** [fwcd/kotlin-language-server#297]
Hey,

Go To Definition is broken again (at least on Windows). This happens on master.

```
java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/daplf/.m2/repository/org/springframework/spring-web/5.3.6/spring-web-5.3.6.jar
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/daplf/.m2/repository/org/springframework/spring-web/5.3.6/spring-web-5.3.6.jar
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at org.javacs.kt.externalsources.KlsURI.getJarPath(KlsURI.kt:57)
	at org.javacs.kt.externalsources.JarClassContentProvider.contentOf(JarClassContentProvider.kt:38)
	at org.javacs.kt.definition.GoToDefinitionKt.goToDefinition(GoToDefinition.kt:48)
	at org.javacs.kt.KotlinTextDocumentService$definition$1.invoke(KotlinTextDocumentService.kt:128)
	at org.javacs.kt.KotlinTextDocumentService$definition$1.invoke(KotlinTextDocumentService.kt:123)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
```

This worked fine after merging https://github.com/fwcd/kotlin-language-server/pull/292 but afterwards some commit must have broken it.

**Comment by fwcd** [comment]
Thanks for reporting, sorry that it broke again. We should probably set up a test (and Windows CI, if needed) to prevent these kinds of regressions from happening...

Would you mind bisecting for the commit that broke support?

**Comment by daplf** [comment]
@fwcd Thanks for the info! Made a PR with a fix: https://github.com/fwcd/kotlin-language-server/pull/300
