### ISSUE TITLE
Couldn't start client Kotlin Language Client

### ISSUE THREAD

**Issue by jwu-au** [fwcd/kotlin-language-server#299]
Hi,

Just installed the plugin in vscode, somehow it can't start.
I confirm mvn in available in PATH.
```
❯ javac --version
javac 11.0.11
❯ mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.060 s
[INFO] Finished at: 2021-07-02T17:48:32+10:00
[INFO] ------------------------------------------------------------------------
```

The detail errors are below, can you point out how can I diagnosis the error?
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[Info  - 5:39:03 PM] main      Adding script definitions [ScriptTemplateWithArgs]
[Info  - 5:39:03 PM] main      Kotlin Language Server: Version 1.1.2
[Info  - 5:39:03 PM] main      Connected to client
[Info  - 5:39:03 PM] async0    Adding workspace folder xxxx
[Info  - 5:39:07 PM] async0    Adding 38 files under xxxxx to source path
[Info  - 5:39:07 PM] async0    Searching for dependencies and Java sources in workspace root /Volumes/workplace/SantosRainbow
Jul. 02, 2021 5:39:12 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:129)
	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:128)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.getMvnCommand(MavenClassPathResolver.kt:128)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.generateMavenDependencyList(MavenClassPathResolver.kt:106)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.access$generateMavenDependencyList(MavenClassPathResolver.kt:1)
	at org.javacs.kt.classpath.MavenClassPathResolver.getClasspathWithSources(MavenClassPathResolver.kt:37)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:116)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more

[Error - 5:39:12 PM] async0    Internal error: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
[Error - 5:39:12 PM] java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
[Error - 5:39:12 PM] 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
[Error - 5:39:12 PM] 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
[Error - 5:39:12 PM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
[Error - 5:39:12 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Error - 5:39:12 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Error - 5:39:12 PM] 	at java.base/java.lang.Thread.run(Thread.java:829)
[Error - 5:39:12 PM] Caused by: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:129)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:128)
[Error - 5:39:12 PM] 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.MavenClassPathResolverKt.getMvnCommand(MavenClassPathResolver.kt:128)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.MavenClassPathResolverKt.generateMavenDependencyList(MavenClassPathResolver.kt:106)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.MavenClassPathResolverKt.access$generateMavenDependencyList(MavenClassPathResolver.kt:1)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.MavenClassPathResolver.getClasspathWithSources(MavenClassPathResolver.kt:37)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
[Error - 5:39:12 PM] 	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
[Error - 5:39:12 PM] 	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
[Error - 5:39:12 PM] 	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
[Error - 5:39:12 PM] 	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
[Error - 5:39:12 PM] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:116)
[Error - 5:39:12 PM] 	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
[Error - 5:39:12 PM] 	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
[Error - 5:39:12 PM] 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
[Error - 5:39:12 PM] 	... 3 more
[Error - 5:39:12 PM] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:129)
	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:128)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.getMvnCommand(MavenClassPathResolver.kt:128)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.generateMavenDependencyList(MavenClassPathResolver.kt:106)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.access$generateMavenDependencyList(MavenClassPathResolver.kt:1)
	at org.javacs.kt.classpath.MavenClassPathResolver.getClasspathWithSources(MavenClassPathResolver.kt:37)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:116)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more

[Error - 5:39:12 PM] Starting client failed
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Unable to find the 'mvn' command
	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:129)
	at org.javacs.kt.classpath.MavenClassPathResolverKt$mvnCommand$2.invoke(MavenClassPathResolver.kt:128)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.getMvnCommand(MavenClassPathResolver.kt:128)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.generateMavenDependencyList(MavenClassPathResolver.kt:106)
	at org.javacs.kt.classpath.MavenClassPathResolverKt.access$generateMavenDependencyList(MavenClassPathResolver.kt:1)
	at org.javacs.kt.classpath.MavenClassPathResolver.getClasspathWithSources(MavenClassPathResolver.kt:37)
	at org.javacs.kt.classpath.UnionClassPathResolver.<init>(ClassPathResolver.kt:57)
	at org.javacs.kt.classpath.ClassPathResolverKt.plus(ClassPathResolver.kt:45)
	at org.javacs.kt.classpath.ClassPathResolverKt.getJoined(ClassPathResolver.kt:40)
	at org.javacs.kt.classpath.DefaultClassPathResolverKt.defaultClassPathResolver(DefaultClassPathResolver.kt:11)
	at org.javacs.kt.CompilerClassPath.refresh(CompilerClassPath.kt:37)
	at org.javacs.kt.CompilerClassPath.refresh$default(CompilerClassPath.kt:31)
	at org.javacs.kt.CompilerClassPath.addWorkspaceRoot(CompilerClassPath.kt:98)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:116)
	at org.javacs.kt.KotlinLanguageServer$initialize$1.invoke(KotlinLanguageServer.kt:71)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more

[Info  - 5:39:12 PM] client    Awaiting async termination...
[Info  - 5:39:12 PM] client    Awaiting debouncer termination...
[Info  - 5:39:12 PM] client    Awaiting async termination...
```

**Comment by fwcd** [comment]
Is `mvn` in the same `PATH` that vscode sees? E.g. if you use a custom shell in your terminal, these might differ.

**Comment by jwu-au** [comment]
@fwcd I resolved the issue by restarting the mac. Thanks.
