### ISSUE TITLE
Broken behaviour when using unimplemented inheritance

### ISSUE THREAD

**Issue by elken** [fwcd/kotlin-language-server#366]
So using a dummy application generated from https://start.spring.io/ and the below files added:

**IThing.kt**
```kotlin
interface IThing {
    fun behaviour
}
```

**Thing.kt**
```kotlin
class Thing : IThing
```

trying to invoke a code action in emacs throws the exception below:

```
async2    Internal error: org.javacs.kt.util.KotlinLSException: Error while analyzing: class Thing : IThing
java.util.concurrent.CompletionException: org.javacs.kt.util.KotlinLSException: Error while analyzing: class Thing : IThing
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.javacs.kt.util.KotlinLSException: Error while analyzing: class Thing : IThing
	at org.javacs.kt.compiler.Compiler.compileKtExpression(Compiler.kt:544)
	at org.javacs.kt.CompiledFile.bindingContextOf(CompiledFile.kt:45)
	at org.javacs.kt.CompiledFile.referenceAtPoint(CompiledFile.kt:68)
	at org.javacs.kt.hover.HoversKt.hoverAt(Hovers.kt:25)
	at org.javacs.kt.KotlinTextDocumentService$hover$1.invoke(KotlinTextDocumentService.kt:102)
	at org.javacs.kt.KotlinTextDocumentService$hover$1.invoke(KotlinTextDocumentService.kt:97)
	at org.javacs.kt.util.AsyncExecutor.compute$lambda-2(AsyncExecutor.kt:19)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 3 more
Caused by: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (1,3) in /dummy.virtual.kt

Attachments:
expression.kt
class Thing : IThing
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.logOrThrowException(ExpressionTypingVisitorDispatcher.java:253)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.lambda$getTypeInfo$0(ExpressionTypingVisitorDispatcher.java:224)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:101)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:164)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:147)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingServices.getTypeInfo(ExpressionTypingServices.java:120)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingServices.getTypeInfo(ExpressionTypingServices.java:95)
	at org.javacs.kt.compiler.Compiler.compileKtExpression(Compiler.kt:533)
	... 10 more
Caused by: java.lang.UnsupportedOperationException: Should not be called
	at org.jetbrains.kotlin.resolve.lazy.NoTopLevelDescriptorProvider.shouldNotBeCalled(TopLevelDescriptorProvider.kt:36)
	at org.jetbrains.kotlin.resolve.lazy.NoTopLevelDescriptorProvider.getPackageFragment(TopLevelDescriptorProvider.kt:39)
	at org.jetbrains.kotlin.resolve.DeclarationResolver.getTopLevelDescriptorsByFqName(DeclarationResolver.kt:107)
	at org.jetbrains.kotlin.resolve.DeclarationResolver.checkRedeclarationsInPackages(DeclarationResolver.kt:86)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:216)
	at org.jetbrains.kotlin.types.expressions.LocalClassifierAnalyzer.processClassOrObject(LocalClassifierAnalyzer.kt:120)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorForStatements.visitClass(ExpressionTypingVisitorForStatements.java:167)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorForStatements.visitClass(ExpressionTypingVisitorForStatements.java:68)
	at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:20)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.lambda$getTypeInfo$0(ExpressionTypingVisitorDispatcher.java:175)
	... 16 more
..orker-19Excluding symbol com.android.tools.build.bundletool.validation.AutoValue_TextureCompressionFormatParityValidator_SupportedTextureCompressionFormats from index since its name is too long
```

Java version:
```
openjdk 11.0.11 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)
```

Environment:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/2872862/174279432-11c3adff-7e6b-4f50-94f5-c4a2f20bf48a.png">
Emacs 28.1 (built from nix)

**Comment by elken** [comment]
It doesn't just apply to the original issue, it applies to (in the project I work on) every operation in every file.

The stack traces that have been thrown are exactly the same, except the code they complain about is different.

On looking at other issues, I'm _far_ from a kotlin expert but I can at least lend my emacs expertise for sure :) A useful starting point to understand what's happening would be appreciated!

**Comment by themkat** [comment]
The indexing often takes a tiny bit of time to complete as well, especially for the "add missing imports"-quickfix. Did you wait for it to finish? Also, there aren't that many code actions. The only one two that works for me without issue is the add missing import and implement abstract members one. 


To fix the issue with the "Implement abstract members" code action not showing up (unless marking the code described above), I would start by looking at the Range-calculations in [the quickfix for implement abstract members](https://github.com/fwcd/kotlin-language-server/blob/main/server/src/main/kotlin/org/javacs/kt/codeaction/quickfix/ImplementAbstractMembersQuickFix.kt#L39) ([the tests](https://github.com/fwcd/kotlin-language-server/blob/main/server/src/test/kotlin/org/javacs/kt/QuickFixesTest.kt) might also be a bit of help when it comes to what LSP type requests are sent, and the parameters).  Now it checks that the range is exactly a given bound at the moment. To my experience, Emacs does not give the same range, but gives the position of the cursor. VSCode on the other hand gives these ranges like expected. Should the fix be in lsp-mode in Emacs? I'm unsure, but based upon my experience of implementing "add missing imports", it should be pretty straightforward to make it work like expected in Emacs without changing lsp-mode. Could probably fix it myself, but I would be super happy if you do instead 🙂  More people getting familiar with the codebase and possibly contributing is awesome! 


Let me know if you need additional details 🙂  Hope the above makes sense. My brain is tired after work and the heat here 😛

**Comment by elken** [comment]
> Did you wait for it to finish?

No idea how long that is meant to take, but yeah this has been a project left in emacs for days :stuck_out_tongue: 

> Also, there aren't that many code actions

I know there are at least a few, but no matter what I do (outside of the "perfect" project), even though the server complains about things, everything always says "no actions available"

As for the rest, I'll try and find time to look into it :D

**Comment by themkat** [comment]
@elken , did you find time to look into it? 🙂 If not, I will probably take a look at it very soon. Gotten way too tired of having to do the workaround I described above for the "Implement abstract members" code action to show up 😛

**Comment by elken** [comment]
Have been super busy and don't use kotlin anymore now 😅 

I can be around to help test stuff!
