### ISSUE TITLE
The Lsp can't start

### ISSUE THREAD

**Issue by AndrewX98** [fwcd/kotlin-language-server#579]
I am using VS code with the latest Kotlin-language-server extension.

Kotlin version: **2.0.0**
Java version: **22.0.1**

This is the VS Code Kotlin output.

`[Trace - 5:26:52 PM] Sending request 'initialize - (0)'.
Java HotSpot(TM) 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
ERROR: transport error 103: invalid port number specified
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [s\open\src\jdk.jdwp.agent\share\native\libjdwp\debugInit.c:700]
[Info  - 5:26:55 PM] Connection to server got closed. Server will restart.
[Error - 5:26:55 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:26:55 PM] Kotlin Language Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 5:26:55 PM] Sending request 'initialize - (0)'.
[Error - 5:26:59 PM] Client Kotlin Language Client: connection to server is erroring. Shutting down server.
[Error - 5:26:59 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at k.shutdown (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-languageclient\lib\common\client.js:897:19)
    at k.stop (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-languageclient\lib\common\client.js:868:21)
    at k.stop (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-languageclient\lib\node\main.js:148:22)
    at k.handleConnectionError (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-languageclient\lib\common\client.js:1104:18)
    at errorHandler (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-languageclient\lib\common\client.js:1047:18)
    at apply (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-languageclient\lib\common\client.js:1417:36)
    at o.call [as invoke] (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at n.fire (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at apply (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-jsonrpc\lib\common\connection.js:299:22)
    at o.call [as invoke] (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-jsonrpc\lib\common\events.js:55:39)
    at n.fire (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-jsonrpc\lib\common\events.js:117:36)
    at g.fireError (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:36:27)
    at Socket.<anonymous> (c:\Users\Andre\.vscode\extensions\fwcd.kotlin-0.2.34\node_modules\vscode-jsonrpc\lib\common\messageWriter.js:73:47)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Java HotSpot(TM) 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
ERROR: transport error 103: invalid port number specified
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [s\open\src\jdk.jdwp.agent\share\native\libjdwp\debugInit.c:700]
[Info  - 5:26:59 PM] Connection to server got closed. Server will restart.
[Error - 5:26:59 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:26:59 PM] Kotlin Language Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 5:27:00 PM] Sending request 'initialize - (0)'.
Java HotSpot(TM) 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
ERROR: transport error 103: invalid port number specified
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [s\open\src\jdk.jdwp.agent\share\native\libjdwp\debugInit.c:700]
[Info  - 5:27:04 PM] Connection to server got closed. Server will restart.
[Error - 5:27:04 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:27:04 PM] Kotlin Language Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:27:04 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 5:27:04 PM] Sending request 'initialize - (0)'.
Java HotSpot(TM) 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
ERROR: transport error 103: invalid port number specified
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [s\open\src\jdk.jdwp.agent\share\native\libjdwp\debugInit.c:700]
[Info  - 5:27:05 PM] Connection to server got closed. Server will restart.
[Error - 5:27:05 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:27:05 PM] Kotlin Language Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:27:05 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 5:27:05 PM] Sending request 'initialize - (0)'.
Java HotSpot(TM) 64-Bit Server VM warning: Option -Xdebug was deprecated in JDK 22 and will likely be removed in a future release.
ERROR: transport error 103: invalid port number specified
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [s\open\src\jdk.jdwp.agent\share\native\libjdwp\debugInit.c:700]
[Error - 5:27:07 PM] The Kotlin Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 5:27:07 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:27:07 PM] Kotlin Language Client client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:27:07 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 `

Any help would be appreciated.

**Comment by diamond2sword** [comment]
Also happened to me. I tried using cocnvim and installed coc-kotlin. Downloaded the 1.3.7 lsp, amd changed the coc-kotlin config through ':CocList extensions' and '\t' and 'c', and changing server bin path to the lsp bin I downloaded. It worked but it keeps on getting stucked on updating classpath
